name: {{__appname__}}
version: {{__version__}}
deps:
  - https://raw.githubusercontent.com/Mons/tnt-config/master/config-scm-1.rockspec
  - https://raw.githubusercontent.com/Mons/tnt-package-reload/master/package.reload-scm-1.rockspec
tntdeps: {}
